DROP DATABASE IF EXISTS ecommerce;
CREATE DATABASE ecommerce; 
USE ecommerce;

CREATE TABLE Cliente(
IDCliente INT UNSIGNED NOT NULL AUTO_INCREMENT,
email VARCHAR(191) NOT NULL,
password VARCHAR(191) NOT NULL,
PRIMARY KEY (IDCliente),
UNIQUE (email)
) ENGINE=InnoDB DEFAULT charset=utf8mb4;


CREATE TABLE Città(
IDCittà INT UNSIGNED NOT NULL AUTO_INCREMENT,
NomeCittà VARCHAR(191) NOT NULL,
PRIMARY KEY (IDCittà)
) Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Provincia(
IDProvincia INT UNSIGNED NOT NULL AUTO_INCREMENT,
Provincia VARCHAR(2) NOT NULL,
PRIMARY KEY (IDProvincia)
) Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE CAP(
IDCap INT UNSIGNED NOT NULL AUTO_INCREMENT,
CAP VARCHAR(5) NOT NULL,
IDCittà INT UNSIGNED NOT NULL,
IDProvincia INT UNSIGNED NOT NULL,
PRIMARY KEY (IDCap),
FOREIGN KEY (IDCittà) REFERENCES Città(IDCittà)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (IDProvincia) REFERENCES Provincia(IDProvincia) ON DELETE CASCADE ON UPDATE CASCADE
) Engine=InnoDB DEFAULT charset=utf8mb4;



CREATE TABLE DatiAnagrafici(
IDCliente INT UNSIGNED NOT NULL, 
nome VARCHAR(191), 
cognome VARCHAR(191), 
indirizzo VARCHAR(191), 
telefono1 VARCHAR(191), 
telefono2 VARCHAR(191), 
IDCittà INT UNSIGNED,
PRIMARY KEY (IDCliente),
FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (IDCittà) REFERENCES Città(IDCittà)
ON DELETE SET NULL

) Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE RubricaIndirizzi(
IDIndirizzo INT UNSIGNED NOT NULL AUTO_INCREMENT, 
IDCliente INT UNSIGNED NOT NULL, 
nominativo VARCHAR(191), 
nome VARCHAR(191), 
cognome VARCHAR(191), 
indirizzo VARCHAR(191), 
IDCittà INT UNSIGNED,
PRIMARY KEY (IDIndirizzo),
FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (IDCittà) REFERENCES Città(IDCittà)
ON DELETE SET NULL
) Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Categoria(
IDCategoria INT UNSIGNED NOT NULL AUTO_INCREMENT, 
NomeCategoria VARCHAR(191), 
DescrizioneCategoria TEXT,
PRIMARY KEY (IDCategoria)
) Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Prodotto(
IDProdotto INT UNSIGNED NOT NULL AUTO_INCREMENT,
NomeProdotto VARCHAR(191), 
Forma VARCHAR(50), 
Prezzo FLOAT(7,2),
PercorsoImmagine VARCHAR(191),
DescrizioneBreveProdotto VARCHAR(255),
DescrizioneDettagliataProdotto TEXT, 
IDCategoria INT UNSIGNED,
PRIMARY KEY (IDProdotto),
FOREIGN KEY (IDCategoria) REFERENCES Categoria(IDCategoria)
ON DELETE CASCADE ON UPDATE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;



CREATE TABLE Valutazione(
IDProdotto INT UNSIGNED NOT NULL, 
IDCliente INT UNSIGNED NOT NULL, 
DataCommento DATETIME, 
Commento TEXT, 
Voto TINYINT(1),
PRIMARY KEY (IDProdotto, IDCliente),
FOREIGN KEY (IDProdotto) REFERENCES Prodotto(IDProdotto)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente)
ON DELETE CASCADE ON UPDATE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Coupon(
IDCoupon INT UNSIGNED NOT NULL AUTO_INCREMENT, 
Sconto TINYINT(1), 
CodiceCoupon VARCHAR(30),
PRIMARY KEY(IDCoupon)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Sconto(
IDSconto INT UNSIGNED NOT NULL AUTO_INCREMENT,
IDCliente INT UNSIGNED NOT NULL,
IDCoupon INT UNSIGNED NOT NULL,
PRIMARY KEY (IDSconto),
FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (IDCoupon) REFERENCES Coupon(IDCoupon)
ON DELETE CASCADE ON UPDATE CASCADE,
UNIQUE(IDCliente, IDCoupon)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE StatusOrdine(
IDStatusOrdine INT UNSIGNED NOT NULL AUTO_INCREMENT, 
statusOrdine VARCHAR(40),
PRIMARY KEY(IDStatusOrdine)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Ordine(
IDOrdine INT UNSIGNED NOT NULL AUTO_INCREMENT, 
dataInserimento DATETIME, 
`Status` INT UNSIGNED,
IDCliente INT UNSIGNED NOT NULL,
IDSconto INT UNSIGNED,
PRIMARY KEY(IDOrdine),
FOREIGN KEY(`Status`) REFERENCES StatusOrdine(IDStatusOrdine) ON DELETE SET NULL,
FOREIGN KEY(IDCliente) REFERENCES Cliente(IDCliente)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(IDSconto) REFERENCES Sconto(IDSconto)
ON DELETE SET NULL
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Composizione(
IDOrdine INT UNSIGNED NOT NULL, 
IDProdotto INT UNSIGNED NOT NULL, 
quantità INT UNSIGNED,
PRIMARY KEY(IDOrdine, IDProdotto),
FOREIGN KEY(IDOrdine) REFERENCES Ordine(IDOrdine)
ON DELETE CASCADE,
FOREIGN KEY(IDProdotto) REFERENCES Prodotto(IDProdotto)
ON DELETE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE MetodoPagamento(
IDMetodoPagamento INT UNSIGNED NOT NULL AUTO_INCREMENT, 
NomeMetodoPagamento VARCHAR(191),
PRIMARY KEY(IDMetodoPagamento)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Pagamento(
IDPagamento INT UNSIGNED NOT NULL AUTO_INCREMENT, 
ImportoPagamento FLOAT(8,2), 
DataPagamento DATETIME, 
IDMetodoPagamento INT UNSIGNED, 
IDOrdine INT UNSIGNED NOT NULL,
PRIMARY KEY(IDPagamento),
FOREIGN KEY(IDMetodoPagamento) REFERENCES MetodoPagamento(IDMetodoPagamento) ON DELETE SET NULL,
FOREIGN KEY(IDOrdine) REFERENCES Ordine(IDOrdine)
ON DELETE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;
CREATE TABLE MetodoSpedizione(
IDMetodoSpedizione INT UNSIGNED NOT NULL AUTO_INCREMENT,
NomeMetodoSpedizione VARCHAR(191), 
SpeseSpedizione FLOAT(7,2),
PRIMARY KEY(IDMetodoSpedizione)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Spedizione(
IDSpedizione INT UNSIGNED NOT NULL AUTO_INCREMENT,
DataSpedizione DATETIME, 
IDTipoSpedizione INT UNSIGNED, 
IDOrdine INT UNSIGNED,
PRIMARY KEY(IDSpedizione),
FOREIGN KEY(IDTipoSpedizione) REFERENCES MetodoSpedizione(IDMetodoSpedizione)
ON DELETE SET NULL,
FOREIGN KEY(IDOrdine) REFERENCES Ordine(IDOrdine)
ON DELETE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Magazzino(
IDMagazzino INT UNSIGNED NOT NULL AUTO_INCREMENT,
PRIMARY KEY(IDMagazzino)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Locazione(
IDProdotto INT UNSIGNED NOT NULL, 
IDMagazzino INT UNSIGNED NOT NULL, 
Disponibilità INT UNSIGNED,
PRIMARY KEY(IDProdotto, IDMagazzino),
FOREIGN KEY(IDProdotto) REFERENCES Prodotto(IDProdotto)
ON DELETE CASCADE,
FOREIGN KEY(IDMagazzino) REFERENCES Magazzino(IDMagazzino) ON DELETE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Vetrina(
IDVetrina INT UNSIGNED NOT NULL AUTO_INCREMENT, 
NomeVetrina VARCHAR(191),
PRIMARY KEY(IDVetrina)
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE TABLE Evidenza(
IDProdotto INT UNSIGNED NOT NULL,
IDVetrina INT UNSIGNED NOT NULL, 
testoInEvidenza TEXT,
PRIMARY KEY(IDProdotto, IDVetrina),
FOREIGN KEY(IDProdotto) REFERENCES Prodotto(IDProdotto)
ON DELETE CASCADE,
FOREIGN KEY(IDVetrina) REFERENCES Vetrina(IDVetrina)
ON DELETE CASCADE
)Engine=InnoDB DEFAULT charset=utf8mb4;

CREATE INDEX index_nomeProdotto ON Prodotto(NomeProdotto)
USING BTREE;

CREATE INDEX index_descrizioneBreve ON Prodotto(DescrizioneBreveProdotto) USING BTREE;