version: '2'

services:
  mysql_p2:
    build: ./mysql-db
    container_name: mysql_p2
    volumes:
      - ${HOME}/data/mysql-p2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  python_app:
    build: ./sql-py
    container_name: python_app
    environment:
      - MYSQL_HOST=mysql_p2
    tty: true
  